name: covidinfo
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  bottom_navy_bar: ^5.4.0
  material_design_icons_flutter: ^4.0.5045
  font_awesome_flutter: ^8.8.1
  country_icons: ^1.1.1
  http: ^0.12.0+2
  fl_chart: ^0.8.7
  webview_flutter: ^0.3.0
  transparent_image: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/


